[package]
name = "games"
version = "0.1.0"
authors = ["lunarised <j@p7.co.nz>"]
edition = "2019"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.5"
